//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCCovid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public long ID { get; set; }
        public Nullable<long> RoomID { get; set; }
        public Nullable<long> UserID { get; set; }
        public string Text { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual User User { get; set; }
    }
}
